// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj1w3Ge_hdNAcf4Cl7S6vhuLKdpxcPUy0',
    appId: '1:456242029808:web:3294eb1fc38aa74b200e35',
    messagingSenderId: '456242029808',
    projectId: 'wattwise-6bc0a',
    authDomain: 'wattwise-6bc0a.firebaseapp.com',
    storageBucket: 'wattwise-6bc0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVNnXxGNlbpr__GiDYS-Y9E4tl_S4JJ-E',
    appId: '1:456242029808:android:066c1ab2cf8d5ced200e35',
    messagingSenderId: '456242029808',
    projectId: 'wattwise-6bc0a',
    storageBucket: 'wattwise-6bc0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa5XOCq6_PEqg_EYZj4XZgKKY8PzMjmSI',
    appId: '1:456242029808:ios:eaa8dbd39573ebc6200e35',
    messagingSenderId: '456242029808',
    projectId: 'wattwise-6bc0a',
    storageBucket: 'wattwise-6bc0a.firebasestorage.app',
    iosBundleId: 'com.example.wattwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa5XOCq6_PEqg_EYZj4XZgKKY8PzMjmSI',
    appId: '1:456242029808:ios:eaa8dbd39573ebc6200e35',
    messagingSenderId: '456242029808',
    projectId: 'wattwise-6bc0a',
    storageBucket: 'wattwise-6bc0a.firebasestorage.app',
    iosBundleId: 'com.example.wattwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj1w3Ge_hdNAcf4Cl7S6vhuLKdpxcPUy0',
    appId: '1:456242029808:web:c2d6a361b3dee72e200e35',
    messagingSenderId: '456242029808',
    projectId: 'wattwise-6bc0a',
    authDomain: 'wattwise-6bc0a.firebaseapp.com',
    storageBucket: 'wattwise-6bc0a.firebasestorage.app',
  );
}
